listofMagicThings = {
    '1': 'Adder stone',
    '2': 'Amulet',
    '3': 'Athame',
    '4': 'Bezoar',
    '5': 'Billy\'s Boots',
    '6': 'Black cat bone',
    '7': 'Black Crochan',
    '8': 'Boline',
    '9': 'Broom',
    '10': 'Cap of invisibility',
    '11': 'Magic carpet',
    '12': 'Cauldron',
    '13': 'Cloak of invisibility',
    '14': 'Cohuleen druith',
    '15': 'Crepundia',
    '16': 'Dried cat',
    '17': 'Dyrnwyn',
    '18': 'For a Swarm of Bees',
    '19': 'Frog coffin',
    '20': 'The Galoshes of Fortune',
    '21': 'Golden Pelydryn',
    '22': 'Grimoire',
    '23': 'Hand of Glory',
    '24': 'Hōko (doll)',
    '25': 'Incantation bowl',
    '26': 'Lamen',
    '27': 'Magic circle',
    '28': 'Magic Mirror',
    '29': 'One Ring',
    '30': 'Palantír',
    '31': 'Pentacle',
    '32': 'Magic ring',
    '33': 'Ring of Gyges',
    '34': 'Ruby slippers',
    '35': 'Ruyi Jingu Bang',
    '36': 'Scottish painted pebbles',
    '37': 'Seal of Solomon',
    '38': 'Seven-league boots',
    '39': 'Silver Shoes',
    '40': 'Magic sword',
    '41': 'Talisman',
    '42': 'Tarnhelm',
    '43': 'The Ebony Horse',
    '44': 'Toadstone',
    '45': 'Triforce',
    '46': 'Witch hat',
    '47': 'Uchide no kozuchi',
    '48': 'Wand',
    '49': 'Wish Way',
    '50': 'Magical tools in Wicca'
}
